### ISSUE TITLE
return isn't a key on the TI-Nspire

### ISSUE THREAD

**Issue by Anonymous941** [CommandOfNature/TI-nspire-RPN-Calculator#1]
In the "Non-obvious keybindings" section of the readme:

> Pop - return

There isn't a key named "return" on the TI-Nspire.  Which key are you referring to?

**Comment by AlexHickie** [comment]
The return key is <kbd>↵</kbd> in the bottom right of the alphabet section.
TI follows the old standards from the typewriter/teletype era, which different countries implemented differently in modern keyboard layouts. [History of the enter key](https://en.wikipedia.org/wiki/Enter_key). I've updated the readme to clarify.

**Comment by Anonymous941** [comment]
> 
> 
> The return key is ↵ in the bottom right of the alphabet section.
> TI follows the old standards from the typewriter/teletype era, which different countries implemented differently in modern keyboard layouts. [History of the enter key](https://en.wikipedia.org/wiki/Enter_key). I've updated the readme to clarify.

Okay, thanks.
